const brainrotTerms = [
  "Ballerina Capuchina",
  "Bobrini Cocosini",
  "Bobritto Bandito",
  "Bombardiro Crocodilo",
  "Bombombini Gusini",
  "Boneca Ambalabu",
  "Broccoli Assassini",
  "Brr Brr Patapim",
  "Burbaloni Luliloli",
  "Burger Hotspot",
  "Burrito Hotspot",
  "Cappuccino Assassino",
  "Chimpazini Bananini",
  "Cocofanto Elefanto",
  "Crocodildo Penisini",
  "El Bobrito",
  "Espressona Signora",
  "Frigo Camello",
  "Glorbo Fruttodrillo",
  "La Vaca Saturno Saturnita",
  "Lirili Larila",
  "Orangutini Ananasini",
  "Spijuniro Golubiro",
  "Ta Ta Ta Sahur",
  "Tracotocutulo",
  "Tralalero Tralala",
  "Trippi Troppi",
  "Trippi Troppi Troppa Trippa",
  "Trulimero Trulichina",
  "Tung Tung Tung Sahur",
  "Urangotini Ananasini",
];

const brainrotImageMap = {
  "Ballerina Capuchina": "ballerina-capuchina.png",
  "Bobrini Cocosini": "bobrini-cocosini.webp",
  "Bobritto Bandito": "bobritto-bandito.webp",
  "Bombardiro Crocodilo": "bombardiro-crocodilo.webp",
  "Bombombini Gusini": "bombombini-gusini.webp",
  "Boneca Ambalabu": "boneca-ambalabu.png",
  "Broccoli Assassini": "broccoli-assassini.png",
  "Brr Brr Patapim": "brr-brr-patapim.png",
  "Burbaloni Luliloli": "burbaloni-luliloli.png",
  "Burger Hotspot": "burger-hotspot.webp",
  "Burrito Hotspot": "burrito-hotspot.webp",
  "Cappuccino Assassino": "cappuccino-assassino.png",
  "Chimpazini Bananini": "chimpazini-bananini.webp",
  "Cocofanto Elefanto": "cocofanto-elefanto.png",
  "Crocodildo Penisini": "crocodildo-penisini.webp",
  "El Bobrito": "el-bobrito.webp",
  "Espressona Signora": "espressona-signora.webp",
  "Frigo Camello": "frigo-camello.webp",
  "Glorbo Fruttodrillo": "glorbo-fruttodrillo.webp",
  "La Vaca Saturno Saturnita": "la-vaca-saturno-saturnita.webp",
  "Lirili Larila": "lirili-larila.webp",
  "Orangutini Ananasini": "orangutini-ananasini.png",
  "Spijuniro Golubiro": "spijuniro-golubiro.webp",
  "Ta Ta Ta Sahur": "ta-ta-ta-sahur.png",
  "Tracotocutulo": "tracotocutulo.webp",
  "Tralalero Tralala": "tralalero-tralala.webp",
  "Trippi Troppi": "trippi-troppi.webp",
  "Trippi Troppi Troppa Trippa": "trippi-troppi-troppa-trippa.png",
  "Trulimero Trulichina": "trulimero-trulichina.png",
  "Tung Tung Tung Sahur": "tung-tung-tung-sahur.png",
  "Urangotini Ananasini": "urangotini-ananasini.webp",
};
